version: '3'

services:
  frontend:
    image: psybinh/udavid-frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
  
  backend:
    image: psybinh/udavid-backend
    ports:
      - 8080:8080
