version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
        name: Build docker container for each microservices
        command: |
          echo "--------- The images is Building ------------"

          docker build -t udavid-backend ./frontend
          docker tag udavid-backend psybinh/udavid-frontend

          docker build -t udavid-backend ./backend
          docker tag udavid-backend psybinh/udavid-backend

          docker login -u psybinh -p $DOCKERPASS

          echo "-------------- Pushing images to dockerhub-------"

          docker push psybinh/udavid-frontend
          docker push psybinh/udavid-backend

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build